### ISSUE TITLE
Unit Test with CI Simple Module 

### ISSUE THREAD

**Issue by rafaelbaiolim** [kenjis/codeigniter-simple-module#1]
Ahn , you or anyone tried to test  this approach of CI with php-unit , or other library for tests ?

**Comment by kenjis** [comment]
This approach uses only CodeIgniter functionalities, so I think [ci-phpunit-test](https://github.com/kenjis/ci-phpunit-test) works fine.
If it does not work, it must be a bug.

**Comment by rafaelbaiolim** [comment]
I see , well , thank you , i really enjoyed your work and yours repositories content , always helps me a lot of .

Keep coding @fromBrazil
